name: health_connection
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  responsive_framework: ^0.2.0
  intl: ^0.17.0
  provider: ^6.0.5
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  flutter_form_builder: any
  form_builder_validators: any
  get_storage: ^2.1.1
  cloud_firestore: ^4.4.5
  google_sign_in: ^6.0.0
  flutter_svg: ^1.1.6
  fluttertoast: ^8.2.1
  country_code_picker: 3.0.0
  google_sign_in_web:  any
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/svg_icons/
    - assets/icons/
    - assets/
  uses-material-design: true

